### ISSUE TITLE
[Feature Request] ClickHouse support

### ISSUE THREAD

**Issue by Slach** [Canner/vulcan-sql#138]
## What’s the problem you're trying to solve
ClickHouse blazing fast analytics database
I would like to support easy analytics API creation with your great project

## Describe the solution you’d like
https://clickhouse.com/docs/en/integrations/language-clients/nodejs

**Comment by wwwy3y3** [comment]
hi, @Slach thank you for your suggestion. 

We'll definitely consider Clickhouse as the following data source to support.

--
If anyone else thinks it's a critical feature to support. Please upvote this issue to let VulcanSQL Team know the priority.

**Comment by wwwy3y3** [comment]
@Slach Thank you for your concern. Currently, we have added caching layer, catalog, and other functionalities. We are in the process of revamping the website and preparing a demo environment, etc recently. We will announce our roadmap, which will include discussions about ClickHouse support.

I will definitely notify you once we have any updates. I just wanted to let you know that we value the feedback from the community and our members are discussing how to have more transparent communication with the community. Please give us some time to sort things out 😎

**Comment by onlyjackfrost** [comment]
@Slach  just let you know that we are working on adding ClickHouse as a data source in VulcanSQL. Once this feature is completed, we would be delighted to invite you to try it out. 🚀

**Comment by kokokuo** [comment]
Hi @Slach,

I wanted to let you know that our ClickHouse Connector is now complete at #221 and in the review stage. We are planning to release it next week. 🙂

**Comment by Slach** [comment]
great news, thank you so much for your great efforts

**Comment by kokokuo** [comment]
Hi @Slach and all 

We have released v0.6.0 version and all packages with [extension-driver-clickhouse](https://www.npmjs.com/package/@vulcan-sql/extension-driver-clickhouse) has ready now 🎉
