### ISSUE TITLE
Bigquery connection failing

### ISSUE THREAD

**Issue by Navrooz** [Canner/vulcan-sql#143]
I have been trying to connect VulcanSQL with BigQuery but receive an error 'Not found'. 

Also, not getting any endpoints in /localhost/doc
![image](https://user-images.githubusercontent.com/4967042/216644022-d6bfbdff-ba73-4591-a8ec-c6fc9cb04444.png)

![image](https://user-images.githubusercontent.com/4967042/216644175-31242919-65d9-4f31-af3b-1dd3f39493f3.png)

The credentials file is working fine as I tested the connection with DBeaver.

- profiles, vulcan, sql and yaml files are at the below link.

Files: https://drive.google.com/drive/folders/1g1lyEG32x63hAzrIo2JK8vFAk5GpNC1U?usp=sharing

**Comment by wwwy3y3** [comment]
hi @Navrooz , thanks for your issue report. We'll check out your attached files and see what's going on.

**Comment by JSYOU** [comment]
Hi @Navrooz, based on your configuration in `vulcan.yaml`, the files `user.sql` and `user.yaml` need to be placed in the `sqls` folder in order for it to run correctly. 

<img width="360" alt="image" src="https://user-images.githubusercontent.com/19495220/216757257-3a863e8f-2eae-4adb-965f-1f077c12468b.png">

Please create a `sqls` folder and move` user.sql` and `user.yaml` into it, then try again. Thank you.

<img width="280" alt="image" src="https://user-images.githubusercontent.com/19495220/216757545-8ff92357-cf9d-4568-93d3-be8da148cb56.png">

**Comment by Navrooz** [comment]
@JSYOU -Hi, Thank you for your reply !
Both the user.sql and user.yaml files are already in sqls folder.
![vulcanTest-1](https://user-images.githubusercontent.com/4967042/216856729-c341c6cf-d0ad-4ee1-9e5c-16d3e2149e4c.png)

**Comment by JSYOU** [comment]
Hi @Navrooz ,
Have you successfully executed your project?

**Comment by Navrooz** [comment]
I tried but as I shared in the screenshots, I get an error 'Not Found' and blank 'localhost:3000/doc' page. It seems like Vulcan is not parsing the endpoint.

**Comment by JSYOU** [comment]
Hi @Navrooz ,
Are you using the `vulcan start` command in the `vulcanTest-1` directory?

We recommend that the working directory be in the same location as the `vulcan.yaml`.

If you want to use the `vulcan start --config ./vulcanTest-1/vulcan.yaml` command from the upper directory, you need to add `./vulcanTest-1/` to the path of `folderPath`, 'profiles', `keyFilename` in `vulcan.yaml` and `profiles.yaml`.

for example: 
`Directory Structure`
<img width="320" alt="image" src="https://user-images.githubusercontent.com/19495220/217145162-ee289618-9823-4765-b8b9-bdbe898d2b9c.png">


`vulcan.yaml`
<img width="320" alt="image" src="https://user-images.githubusercontent.com/19495220/217144926-b9bc875a-d2d1-44a0-835b-1612a1766bc8.png">


`profiles.yaml`
<img width="320" alt="image" src="https://user-images.githubusercontent.com/19495220/217144876-6e0a37be-eab6-4f20-865c-11ab80d80238.png">

**Comment by Navrooz** [comment]
Hi @JSYOU ,

Thank you for your valuable suggestion.

I am executing the `vulcan start` command from the vulcanTest-1 directory which has vulcan.yaml, profiles and creds file in it.The result is still the same (Blank home page with no endpoints and 'Not Found' error on API endpoint). Please let me know if you need any files from my end for investigation. 

![image](https://user-images.githubusercontent.com/4967042/217313068-a96cdc85-0056-46d1-aae3-224b81062429.png)

![image](https://user-images.githubusercontent.com/4967042/217311873-29a71cde-d8e6-4bc2-8093-69bb1ac743af.png)

![image](https://user-images.githubusercontent.com/4967042/217312029-ed811242-84d4-4844-9085-d44256e497f4.png)

![image](https://user-images.githubusercontent.com/4967042/217312079-5ea43a98-bda3-4021-bd1a-cce8abad8b0f.png)

![image](https://user-images.githubusercontent.com/4967042/217312237-e862c1cc-3217-49a9-b9eb-935a01d8a019.png)

**Comment by wwwy3y3** [comment]
hi @Navrooz 
Can you also provide following information ?

- Version:
Use command `vulcan version` to get your packages' version

  ```
  cli version: 0.1.0-alpha.1
  core version: 0.1.0-alpha.1
  build version: 0.1.0-alpha.1
  serve version: 0.1.0-alpha.1
  ```

- OS: macOS, windows 11 ...

**Comment by Navrooz** [comment]
Yes sure. Here's the extract:
OS: Windows 11
![image](https://user-images.githubusercontent.com/4967042/217342513-99338952-392f-41c8-b0b8-bd085e1d2c8b.png)

**Comment by oscar60310** [comment]
It looks like a file listing issue on Windows, we handled it when initializing projects but not for searching sql files.
https://github.com/Canner/vulcan-sql/blob/develop/packages/cli/src/commands/init.ts#L131
https://github.com/Canner/vulcan-sql/blob/develop/packages/build/src/lib/schema-parser/schema-reader/fileSchemaReader.ts#L59

**Comment by Navrooz** [comment]
You are right, the problem is with listing issue .

**1.The demo project https://vulcansql.com/docs/quickstart runs fine. However, if I modify the sql path in vulcan.yaml then I am encountering the same issue as with my project i.e. **no** endpoints appearing in localhost:3000/doc**

![VulcanTesting-1](https://user-images.githubusercontent.com/4967042/218196600-1ac75841-5bd8-4857-b1b9-bcc83ec106f4.png)
![VulcanTesting-2](https://user-images.githubusercontent.com/4967042/218196814-2544fded-25fc-48cd-88e7-a4d2d4d59de8.png)


**2. I changed code as described in your above comment and tried executing the project but no luck.**

![VulcanTesting-5](https://user-images.githubusercontent.com/4967042/218196908-63923567-8c52-4f0b-89a9-f9d5c22300db.png)
![VulcanTesting-6](https://user-images.githubusercontent.com/4967042/218197027-48ec3e05-ad53-4d5c-bafe-d8609df23a71.png)
![VulcanTesting-7](https://user-images.githubusercontent.com/4967042/218197067-ca3a41cb-5afc-4ea4-914b-8572be27bc47.png)

**3.Tried running the project in Linux environment on Windows using WSL. It's not able to install dependencies and fails at building project stage**.

![VulcanTesting-8](https://user-images.githubusercontent.com/4967042/218197116-c88d1c78-97f5-4fe1-8f56-e91745c3762e.png)

**Comment by wwwy3y3** [comment]
@Navrooz We're fixing this windows issue in https://github.com/Canner/vulcan-sql/pull/145.

Please give us some time to do a proper PR review.

We'll release a new version after this PR get merged.

**Comment by wwwy3y3** [comment]
hi @Navrooz thanks for your patience. This windows path issues has been fixed at release [v0.3.2](https://github.com/Canner/vulcan-sql/releases/tag/v0.3.2).

Please upgrade your version and let us know if it resolves your issues. We'll close this issue in a few days if it's resolved or other issues come up unrelated to this windows path parsing issue.

If there are other windows development issues, please do share with us at our discussion thread:  https://github.com/Canner/vulcan-sql/discussions/148

**Comment by Navrooz** [comment]
@wwwy3y3 Thank you for the update!

I am able to establish the connection and receive response now.

**Comment by wwwy3y3** [comment]
@Navrooz Glad to hear that! 

If there are other windows development issues come up, please do let us know at our discussion thread: https://github.com/Canner/vulcan-sql/discussions/148

Closing this issue.
