### ISSUE TITLE
“vulcan” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by mfurkanoztrk** [Canner/vulcan-sql#240]
## Environment
- OS:  macOS with intel chip
- 
## What's wrong?
I installed vulcan from binary and using pip and I can't run it at all.

Exact error is as follows: 

“vulcan” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

**Comment by cyyeh** [comment]
Hi, @mfurkanoztrk You can go to the System Preferences > Security & Privacy > General to allow Apple to open VulcanSQL anyway. Then you just need to the command `vulcan` to install VulcanSQL. I hope this answers your question, thank you!

<img width="725" alt="image" src="https://github.com/Canner/vulcan-sql/assets/11023068/e1d60a59-1efe-48b0-923d-a69cadcb9289">

**Comment by mfurkanoztrk** [comment]
thanks for your support. this resolved my issue when using binary install but not for pip.
