### ISSUE TITLE
[Canner Datasource] Can choose to use cache or not when creating the caching data

### ISSUE THREAD

**Issue by onlyjackfrost** [Canner/vulcan-sql#324]
## Environment

- Version:
  ```
  cli version: 10.0
  core version: 0.10.0
  build version: 10.0
  serve version: 10.0
  ```

- OS: macOS, windows 11 ...

## What's wrong?
I created an API using Vulcan with caching enabled, and the data source is Canner. However, I noticed that when Vulcan updates the cache, the data retrieved is not the latest. On examining the source code, I found that Vulcan uses temporary storage when updating and fetching data from Canner, resulting in non-up-to-date results.  

## What's the correct behavior?
The result shoud be a up-to-date result

**Comment by imAsterSun** [comment]
(sc-12800)[https://app.shortcut.com/canner/story/12800/data-service-api-cache-does-not-update-to-latest-data-after-refresh]
