### ISSUE TITLE
CLI error : "--name" not find

### ISSUE THREAD

**Issue by eastmoon** [Canner/vulcan-sql#67]
### What's wrong?

![image](https://user-images.githubusercontent.com/5998687/189079229-61f109eb-019e-4f78-bbb4-062c41193b3d.png)

### What's the correct behavior?

follow document, this command must ```vulcan init --name <project-name>```, but actually need use ```vulcan init -p <project-name>```.

**Comment by wwwy3y3** [comment]
hi @eastmoon 

Thanks for your attention to VulcanSQL. As I mentioned in https://github.com/Canner/vulcan-sql/issues/66#issuecomment-1241152305. This project is still under construction and will be released in a few weeks.
