### ISSUE TITLE
Documnet error : vulcan need install in global

### ISSUE THREAD

**Issue by eastmoon** [Canner/vulcan-sql#69]
### What's wrong?

![image](https://user-images.githubusercontent.com/5998687/189082583-d9c64ef2-6f1e-4ee7-aae2-348fa480bdd4.png)

### What's the correct behavior?

follow document, install command is ```npm install @vulcan-sql/cli```, but it will install in local place.

But usage command is ```vulcan init```, if modules install in local node_modules, command is ```npx vulcan init``` or write usage command in package.json.

And this project look like a sub-project control tool. Suggest install command modify to ```npm install -g  @vulcan-sql/cli```, it will make usage command right.

![image](https://user-images.githubusercontent.com/5998687/189082973-4cfe4605-d2f4-440b-9654-c2d4cb2481fd.png)

**Comment by wwwy3y3** [comment]
hi @eastmoon 

Thanks for your advice on the document.

VulcanSQL is a monorepo, which includes different sub-modules like building-tools, server, catalog, and also the CLI tool you mentioned. Changing the command in the doc to `npm install -g @vulcan-sql/cli` surely solved the issue you mentioned, but we're also very cautious about keeping the versions of different sub-modules consistent. Not sure if we suggest users install CLI globally and keeping other modules locally will risk versions being inconsistent.

I'll be sure to discuss this matter with other core members and follow up on our discussion later in this thread.
